site_name: Cauliflower
site_url: https://mydomain.org/mysite

######## ---------------------------------------- ########
# Site configuration for MkDocs with Material theme
theme:
  name: material

  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  
  features:
    - navigatio#n.tabs
    - navigation.top
    - navigation.sections
######## ---------------------------------------- ########



######## ---------------------------------------- #######
# Table of Contents configuration
# markdown_extensions:
#   - toc:
#       title: On this page
#       permalink: true
#       toc_depth: 3
######## ---------------------------------------- ########



######## ---------------------------------------- ########
# Enable MathJax support for rendering mathematical expressions
markdown_extensions:
  - toc:
      title: On this page
      permalink: true
      toc_depth: 3

  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
######## ---------------------------------------- ########



######## ---------------------------------------- ########
# document structure
nav:
  - Home: 
    - index.md
  - Large Sample Theory:
    - 空间计量经济学: home/LST2025/LST_Chapter4_SAR.md
    - 矩阵代数: home/LST2025/LST_Chapter4_matrix.md

######## ---------------------------------------- ########
